# Generated by Django 3.0.4 on 2020-03-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_session', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_location', models.CharField(max_length=30)),
                ('request_made', models.TimeField(auto_now=True)),
                ('request_start', models.TimeField(blank=True, default=None, null=True)),
                ('request_end', models.TimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('Waiting Question', 'Waiting Question'), ('Not started', 'Not started'), ('Help needed', 'Help needed'), ('Gave up', 'Gave up'), ('Complete', 'Complete'), ('Serviced', 'Serviced')], default='Not started', max_length=20)),
                ('lab_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.LabSession')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_text', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tempStoreUserLocationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('lab_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.LabSession')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.Person')),
            ],
        ),
        migrations.CreateModel(
            name='RequestHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Person')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Request')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=30)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Request')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Topic')),
            ],
        ),
    ]
